properties ([disableConcurrentBuilds()]) //only one task

pipeline {
    agent {
        label "master"
        //options { timeatamps() }
    }

    //triggers { pollSCM('* * * * *') }

    tools {
        // Note: this should match with the tool name configured in your jenkins instance (JENKINS_URL/configureTools/)
        jdk '1.8.0_212'
        maven '3'
    }

    stages {

        stage('Preparation') {
            git url:  'https://github.com/KosDP1987/spring-petclinic.git'
        }

        stage("mvn build") {
            steps {
                withMaven(maven: '3') {
                    sh "mvn clean install -q"
                }
            }
        }
        stage('Results') {
            junit '**/target/surefire-reports/TEST-*.xml'
            archiveArtifacts 'target/*.jar'
        }

    }

}
